module.exports = window.AppEvents = ArrayToObject([

'UPDATE_APPLICATION',

'UPDATE_BANNER',

'UPDATE_LEFT',

'UPDATE_CENTER',

'UPDATE_RIGHT',

'UPDATE_FOOTER',

'UPDATE_NAVIGATION',

'UPDATE_HOMEPAGE',

'UPDATE_CATITEMSPAGE',

'UPDATE_USERITEMSPAGE',

'UPDATE_ITEMDETAILSPAGE',

'UPDATE_BUYITEMPAGE', 'UPDATE_SELLITEMPAGE',

'UPDATE_MESSAGE', 'SENT_MESSAGE', 'RECEIVED_MESSAGE', 'UPDATE_CHATBAR',

'UPDATE_CHATBOX', 'ADD_CHATBOX', 'SHOW_CHATBOX', 'REMOVE_CHATBOX',

'LOAD_RECENT_MESSAGES', 'LOAD_OLD_MESSAGES',

'UPDATE_ITEM',

'UPDATE_USER',

'UPDATE_LOCATION',

'CHATUSERS_UPDATE', 'CHATUSER_UPDATE', 'CURRENTCHATUSER_UPDATE',

'USERMESSAGES_LOADED', 'USERMESSAGES_ADDED_NEW', 'USERMESSAGES_ADDED_OLD',

]);
